---
title: "Iris_Data_Basic_Analysis"
author: "Nazmul Hossain"
date: "12/01/2021"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = T)
```

### Attach data
```{r}
attach(iris)
```

### Call library
```{r}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(ggridges)
library(Hmisc)
library(corrplot)
library(RColorBrewer)
```


# Understanding data

```{r}
head(iris)
```
```{r}
str(iris)
```

## Summary
```{r}
summary(iris)
```

## Exploratory data analysis
### histogram
```{r}
ggplot(iris, aes(iris$Sepal.Length)) + geom_histogram(col= "red", bins = 30) +
  labs(title = "Sepal length histogram", x= "Sepal length")

```
```{r}
ggplot(iris, aes(iris$Sepal.Width)) + geom_histogram(col ="red", bins = 30) +
  labs(title = "Sepam width histogram", x = "Sepal Width")

```


```{r}
ggplot(iris, aes(iris$Petal.Length)) + geom_histogram(col = "blue", bins = 30) +
  labs(title = "Petal length histogram", x= "Petal length")
```
```{r}
ggplot(iris, aes(iris$Petal.Width)) + geom_histogram(col ="blue", bins = 30) +
  labs(title = "Petal width histogram", x = "Petal width")

```

### Plot
```{r}
ggplot(iris, aes(x=iris$Sepal.Length, fill = Species)) + geom_histogram(position ="identity" ,bins = 30)
```


```{r}
iris$Species <- as.factor(iris$Species)
```

```{r}
ggplot(iris, aes(x = iris$Sepal.Length, y = Species, fill = Species)) + geom_density_ridges(aes(point_color = Species, point_fill = Species,  point_shape = Species),
    alpha = .2, point_alpha = 1, jittered_points = TRUE
  ) +
  scale_point_color_hue(l = 40) +
  scale_discrete_manual(aesthetics = "point_shape", values = c(21, 22, 23))
```

```{r}
ggplot(iris, aes(x = iris$Sepal.Width, y = Species)) +
  geom_density_ridges(
    aes(y = Species, point_shape = Species, point_fill = Species), 
    alpha = .2, point_alpha = 1, jittered_points = T) +
  scale_point_color_hue(l = 40) + scale_point_size_continuous(range = c(0.5, 4)) +
  scale_discrete_manual(aesthetics = "point_shape", values = c(21, 22, 23))
```

```{r}
ggplot(iris, aes(x = iris$Petal.Length, y = Species, fill = Species)) +
  geom_density_ridges(
    aes(point_shape = Species, point_fill = Species, point_size = Petal.Length), 
    alpha = .2, point_alpha = 1, jittered_points = TRUE
  ) +
  scale_point_color_hue(l = 40) + scale_point_size_continuous(range = c(0.5, 4)) +
  scale_discrete_manual(aesthetics = "point_shape", values = c(21, 22, 23))
```

```{r}
ggplot(iris, aes(x = iris$Petal.Width, y = Species, fill = Species)) +
  geom_density_ridges(
    aes(point_shape = Species, point_fill = Species, point_size = Petal.Width), 
    alpha = .2, point_alpha = 1, jittered_points = TRUE
  ) +
  scale_point_color_hue(l = 40) + scale_point_size_continuous(range = c(0.5, 4)) +
  scale_discrete_manual(aesthetics = "point_shape", values = c(21, 22, 23))

```

### Scatterplot
```{r}
ggplot(iris, aes(iris$Sepal.Length, Sepal.Width, shape = Species)) + geom_point(aes(col = Species), size = 5) + xlab("Sepal.Length") + ylab("Sepal.Width") 
```


```{r}
ggplot(iris, aes(iris$Petal.Length, Petal.Width, shape = Species)) + geom_point(aes(col = Species), size = 4) + xlab("Petal.Length") + ylab("Petal.Width") 
```

```{r}
ggplot(iris, aes(iris$Sepal.Length, Petal.Length, shape = Species)) + geom_point(aes(col = Species), size = 4) + xlab("Sepal.Length") + ylab("Petal.Length") 
```

```{r}
ggplot(iris, aes(iris$Sepal.Width, Petal.Width, shape = Species)) + geom_point(aes(col = Species), size= 4) + xlab("Sepal.Width") + ylab("Petal.Width") 
```

### Correlation
```{r}
corr.table <- cor(iris[, 1:4])
```

```{r}
corr.table
```

```{r}
corrplot(corr.table)
```

# Classification
## label encoding
```{r}
iris$Species <- as.factor(iris$Species)
```

```{r}
iris$Species <- as.numeric(iris$Species)
```

## Model building
```{r}
describe(iris)
```
